#!/usr/bin/env python

import getpass
import sys
import lastpass
import ConfigParser
import os.path

config_path_template = '~/.ingpass-helper/config'

def get_user_name():
	config_path = os.path.expanduser(config_path_template)
	parser = ConfigParser.RawConfigParser(allow_no_value=True)
	if os.path.isfile(config_path):
		parser.read(config_path)
		return parser.get('base','user.name')
	else:
		user_name = raw_input('Enter LastPass user name (email): ')
		parser.add_section('base')
		print parser.sections()
		parser.set('base','user.name',user_name)
		with open(config_path,'wb') as config_file:
			parser.write(config_file)
		print 'User name was saved to ' + config_path
		return user_name

def get_lastpass_vault():
	user_name = get_user_name()
	password = getpass.getpass('Enter Lastpass password for user ' + user_name + ':')
	return lastpass.Vault.open_remote(user_name,password)

def print_row(account_id,account_url):
	print account_id.rjust(8,' ') + '|' + account_url.rjust(30,' ')

def search(pattern):
	vault = get_lastpass_vault()
	matched_accounts = filter(lambda a: pattern in a.url, vault.accounts)
	for a in matched_accounts:
		print_row(a.id,a.url)
	
def main():
	search(sys.argv[2])

main()

